# Generated by Django 4.1.1 on 2022-09-26 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('precio', models.FloatField(verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': ' productos',
            },
        ),
        migrations.CreateModel(
            name='Dirtribuir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('codigoProvedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provedores.provedores')),
            ],
            options={
                'verbose_name': 'Distribuir',
                'verbose_name_plural': 'Distribuciones',
            },
        ),
    ]
