# Generated by Django 4.1.1 on 2022-09-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProvedores', models.CharField(help_text='Ingrese el codigo del Provedor', max_length=50)),
                ('nombreProvedores', models.CharField(help_text='Ingrese el Nombre del Provedores', max_length=100)),
                ('apellidoProvedores', models.CharField(help_text='Ingrese el apellido del Provedores', max_length=100)),
                ('direccionProvedores', models.CharField(help_text='Ingrese la Direccion del Provedores', max_length=100)),
                ('provinciaProvedores', models.CharField(help_text='Ingrese el Provincia del Provedores', max_length=100)),
                ('telefonoProvedores', models.CharField(help_text='Ingrese el Telefono del Provedores', max_length=12)),
            ],
            options={
                'verbose_name': 'Provedores',
                'verbose_name_plural': 'Provedores',
            },
        ),
    ]
